export const REQUEST_DAEMON_CONSTANTS = 'REQUEST_DAEMON_CONSTANTS'
export const RECEIVE_DAEMON_CONSTANTS = 'RECEIVE_DAEMON_CONSTANTS'
export const REQUEST_DAEMON_STOP = 'REQUEST_DAEMON_STOP'
export const RECEIVE_DAEMON_STOP = 'RECEIVE_DAEMON_STOP'

